### ISSUE TITLE
Nespolahlivo cita hodnoty

### ISSUE THREAD

**Issue by Baskervil** [ZmurkolDym/swimming-pool#1]
@ZmurkolDym - V skripte plavaren.sh sa nespolahlivo cita hodnota z html stranky. Ked  sa zmeni stranka, tak sa neprecita cislo ale ine znaky zo stranky.
Navrhujem:

1. prikazom grep ziskat riadok s hladanym elementom ```line=$(grep "<h1 id=\"title\">" index.html)```
2. prikazom sed ziskat obsah medzi ```<h1> a </h1>``` napriklad ```sed -e 's/<[^>]*>//g'```
3. awk na odstranenie HTML tagov a získanie cisteho cisla  ```awk '{print $0}'```

Overit spravnost regularneho vyrazu napriklad na https://saschadens.github.io/

**Comment by ZmurkolDym** [comment]
Uprava je v branchy #1.
Prosim otestovať.

**Comment by Baskervil** [comment]
Funguje spravne. Poprosim o merge do main branche
